version: 2

updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "BroderickCarlin"
    commit-message:
      prefix: "chore(Dependabot)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "BroderickCarlin"
    commit-message:
      prefix: "chore(Dependabot)"