name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2
      run: sudo apt-get -y install libsdl2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2
      run: sudo apt-get -y install libsdl2-dev
    - name: Install Clippy
      run: rustup component add clippy
    - name: clippy check
      run: cargo clippy

  formatting: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2
      run: sudo apt-get -y install libsdl2-dev
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check Formatting
      run: cargo fmt --all -- --check


